[2025-04-09 10:30:05,889] 15 root - INFO - >>>>>>> Stage Data Ingestion Stage started
[2025-04-09 10:30:05,923] 17 root - INFO - yaml file: config\config.yaml loaded successfully
[2025-04-09 10:30:05,933] 17 root - INFO - yaml file: params.yaml loaded successfully
[2025-04-09 10:30:05,950] 17 root - INFO - yaml file: schema.yaml loaded successfully
[2025-04-09 10:30:05,950] 29 root - INFO - create directory as: artifacts
[2025-04-09 10:30:05,950] 29 root - INFO - create directory as: artifacts/data_ingestion
[2025-04-09 10:30:36,867] 20 root - ERROR - Error occures script name [D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py] in line no [89] error message [Error occures script name [D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py] in line no [35] error message [ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67f5fed659bde87e71885847, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>]]
Traceback (most recent call last):
  File "D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py", line 35, in export_collection_as_dataframe
    df=pd.DataFrame(list(collection.find()))
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\cursor.py", line 1284, in __next__
    return self.next()
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\cursor.py", line 1260, in next
    if len(self._data) or self._refresh():
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\cursor.py", line 1208, in _refresh
    self._send_message(q)
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\cursor.py", line 1102, in _send_message
    response = client._run_operation(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1896, in _run_operation
    return self._retryable_read(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2005, in _retryable_read
    return self._retry_internal(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1972, in _retry_internal
    ).run()
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2709, in run
    return self._read() if self._is_read else self._write()
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2854, in _read
    self._server = self._get_server()
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 2802, in _get_server
    return self._client._select_server(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\mongo_client.py", line 1791, in _select_server
    server = topology.select_server(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\topology.py", line 409, in select_server
    server = self._select_server(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\topology.py", line 387, in _select_server
    servers = self.select_servers(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
  File "d:\Projects\Phishing_Detector\.venv\lib\site-packages\pymongo\synchronous\topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67f5fed659bde87e71885847, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py", line 89, in initiate_data_ingestion
    dataframe=self.export_collection_as_dataframe()
  File "D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py", line 42, in export_collection_as_dataframe
    raise PhishingException(e,sys)
phishing.exception.exception.PhishingException: Error occures script name [D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py] in line no [35] error message [ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67f5fed659bde87e71885847, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Projects\Phishing_Detector\main.py", line 17, in <module>
    data_ingestion.initiate_data_ingestion_pipline()
  File "D:\Projects\Phishing_Detector\phishing\pipeline\data_ingestion_pipeline.py", line 17, in initiate_data_ingestion_pipline
    data_ingestion.initiate_data_ingestion()
  File "D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py", line 95, in initiate_data_ingestion
    raise PhishingException(e,sys)
phishing.exception.exception.PhishingException: Error occures script name [D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py] in line no [89] error message [Error occures script name [D:\Projects\Phishing_Detector\phishing\components\data_ingestion.py] in line no [35] error message [ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67f5fed659bde87e71885847, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-00.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-01.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('ac-r9iinlc-shard-00-02.2wtuuwb.mongodb.net:27017: timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>]]
